local emojis = {
    { value = "🎨", description = "Improve structure / format of the code.", text = ":art:" },
    { value = "⚡️", description = "Improve performance.", text = ":zap:" },
    { value = "🔥", description = "Remove code or files.", text = ":fire:" },
    { value = "🐛", description = "Fix a bug.", text = ":bug:" },
    { value = "🚑️", description = "Critical hotfix.", text = ":ambulance:" },
    { value = "✨", description = "Introduce new features.", text = ":sparkles:" },
    { value = "📝", description = "Add or update documentation.", text = ":memo:" },
    { value = "🚀", description = "Deploy stuff.", text = ":rocket:" },
    { value = "💄", description = "Add or update the UI and style files.", text = ":lipstick:" },
    { value = "🎉", description = "Begin a project.", text = ":tada:" },
    { value = "✅", description = "Add, update, or pass tests.", text = ":white_check_mark:" },
    { value = "🔒️", description = "Fix security issues.", text = ":lock:" },
    { value = "🔐", description = "Add or update secrets.", text = ":closed_lock_with_key:" },
    { value = "🔖", description = "Release / Version tags.", text = ":bookmark:" },
    { value = "🚨", description = "Fix compiler / linter warnings.", text = ":rotating_light:" },
    { value = "🚧", description = "Work in progress.", text = ":construction:" },
    { value = "💚", description = "Fix CI Build.", text = ":green_heart:" },
    { value = "⬇️", description = "Downgrade dependencies.", text = ":arrow_down:" },
    { value = "⬆️", description = "Upgrade dependencies.", text = ":arrow_up:" },
    { value = "📌", description = "Pin dependencies to specific versions.", text = ":pushpin:" },
    { value = "👷", description = "Add or update CI build system.", text = ":construction_worker:" },
    { value = "📈", description = "Add or update analytics or track code.", text = ":chart_with_upwards_trend:" },
    { value = "♻️", description = "Refactor code.", text = ":recycle:" },
    { value = "➕", description = "Add a dependency.", text = ":heavy_plus_sign:" },
    { value = "➖", description = "Remove a dependency.", text = ":heavy_minus_sign:" },
    { value = "🔧", description = "Add or update configuration files.", text = ":wrench:" },
    { value = "🔨", description = "Add or update development scripts.", text = ":hammer:" },
    { value = "🌐", description = "Internationalization and localization.", text = ":globe_with_meridians:" },
    { value = "✏️", description = "Fix typos.", text = ":pencil2:" },
    { value = "💩", description = "Write bad code that needs to be improved.", text = ":poop:" },
    { value = "⏪️", description = "Revert changes.", text = ":rewind:" },
    { value = "🔀", description = "Merge branches.", text = ":twisted_rightwards_arrows:" },
    { value = "📦️", description = "Add or update compiled files or packages.", text = ":package:" },
    { value = "👽️", description = "Update code due to external API changes.", text = ":alien:" },
    { value = "🚚", description = "Move or rename resources (e.g.: files, paths, routes).", text = ":truck:" },
    { value = "📄", description = "Add or update license.", text = ":page_facing_up:" },
    { value = "💥", description = "Introduce breaking changes.", text = ":boom:" },
    { value = "🍱", description = "Add or update assets.", text = ":bento:" },
    { value = "♿️", description = "Improve accessibility.", text = ":wheelchair:" },
    { value = "💡", description = "Add or update comments in source code.", text = ":bulb:" },
    { value = "🍻", description = "Write code drunkenly.", text = ":beers:" },
    { value = "💬", description = "Add or update text and literals.", text = ":speech_balloon:" },
    { value = "🗃️", description = "Perform database related changes.", text = ":card_file_box:" },
    { value = "🔊", description = "Add or update logs.", text = ":loud_sound:" },
    { value = "🔇", description = "Remove logs.", text = ":mute:" },
    { value = "👥", description = "Add or update contributor(s).", text = ":busts_in_silhouette:" },
    { value = "🚸", description = "Improve user experience / usability.", text = ":children_crossing:" },
    { value = "🏗️", description = "Make architectural changes.", text = ":building_construction:" },
    { value = "📱", description = "Work on responsive design.", text = ":iphone:" },
    { value = "🤡", description = "Mock things.", text = ":clown_face:" },
    { value = "🥚", description = "Add or update an easter egg.", text = ":egg:" },
    { value = "🙈", description = "Add or update a .gitignore file.", text = ":see_no_evil:" },
    { value = "📸", description = "Add or update snapshots.", text = ":camera_flash:" },
    { value = "⚗️", description = "Perform experiments.", text = ":alembic:" },
    { value = "🔍️", description = "Improve SEO.", text = ":mag:" },
    { value = "🏷️", description = "Add or update types.", text = ":label:" },
    { value = "🌱", description = "Add or update seed files.", text = ":seedling:" },
    { value = "🚩", description = "Add, update, or remove feature flags.", text = ":triangular_flag_on_post:" },
    { value = "🥅", description = "Catch errors.", text = ":goal_net:" },
    { value = "💫", description = "Add or update animations and transitions.", text = ":dizzy:" },
    { value = "🗑️", description = "Deprecate code that needs to be cleaned up.", text = ":wastebasket:" },
    {
        value = "🛂",
        description = "Work on code related to authorization, roles and permissions.",
        text = ":passport_control:",
    },
    { value = "🩹", description = "Simple fix for a non-critical issue.", text = ":adhesive_bandage:" },
    { value = "🧐", description = "Data exploration/inspection.", text = ":monocle_face:" },
    { value = "⚰️", description = "Remove dead code.", text = ":coffin:" },
    { value = "🧪", description = "Add a failing test.", text = ":test_tube:" },
    { value = "👔", description = "Add or update business logic.", text = ":necktie:" },
    { value = "🩺", description = "Add or update healthcheck.", text = ":stethoscope:" },
    { value = "🧱", description = "Infrastructure related changes.", text = ":bricks:" },
    { value = "🧑‍💻", description = "Improve developer experience.", text = ":technologist:" },
    { value = "💸", description = "Add sponsorships or money related infrastructure.", text = ":money_with_wings:" },
    { value = "🧵", description = "Add or update code related to multithreading or concurrency.", text = ":thread:" },
    { value = "🦺", description = "Add or update code related to validation.", text = ":safety_vest:" },
}

return emojis
